# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5.QtWidgets import QMessageBox



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scannerButton = QtWidgets.QPushButton(self.centralwidget)
        self.scannerButton.setGeometry(QtCore.QRect(130, 630, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scannerButton.setFont(font)
        self.scannerButton.setObjectName("scannerButton")
        self.inputCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputCodeLabel.setGeometry(QtCore.QRect(90, 40, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.inputCodeLabel.setFont(font)
        self.inputCodeLabel.setObjectName("inputCodeLabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(23, 120, 311, 481))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(353, 120, 301, 481))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 80, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(673, 120, 291, 481))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(716, 82, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.parserButton = QtWidgets.QPushButton(self.centralwidget)
        self.parserButton.setGeometry(QtCore.QRect(980, 690, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.parserButton.setFont(font)
        self.parserButton.setObjectName("parserButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(770, 620, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #scanner button
        self.scannerButton.clicked.connect(self.scannerClicked)
        # save button
        self.saveButton.clicked.connect(self.saveClicked)
        # parser button
        self.parserButton.clicked.connect(self.parserClicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scannerButton.setText(_translate("MainWindow", "Scanner"))
        self.inputCodeLabel.setText(_translate("MainWindow", "Input Code"))
        self.label.setText(_translate("MainWindow", "Output of scanner"))
        self.label_2.setText(_translate("MainWindow", "Put the output by yourself"))
        self.parserButton.setText(_translate("MainWindow", "Parser Tree"))
        self.saveButton.setText(_translate("MainWindow", "Save"))

    def scannerClicked(self):

        #writing in the input file with same name of input file in scanner.cpp
        with open('input.txt','w') as f:
            input_text = self.plainTextEdit.toPlainText()
            f.write(input_text)

        #running the exe file (scanner.cpp)
        os.system("scanner.exe")

        #printing the output file from scanner inside GUI
        output_text = open('tokens.txt').read()
        self.plainTextEdit_2.setPlainText(output_text)



    def saveClicked(self):
        # writing in the output file directly
        with open('tokens.txt','w') as f:
            input_text = self.plainTextEdit_3.toPlainText()
            f.write(input_text)


    def parserClicked(self):
        #code of parsering output file
        os.system('python myParser.py')


if __name__ == "__main__":
    import sys
    import webbrowser
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
